Repository Ligator/olympia, pull requests merged in 2021-03, with the labels that each got.

#55 internacionalizacion
  app/views/cards/_form.html.erb
  app/views/cards/edit.html.erb
  app/views/cards/index.html.erb
  app/views/cards/new.html.erb
  app/views/cards/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_edit.html.erb
  app/views/devise/registrations/_edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/orders/thank_you.html.erb
  app/views/stores/index.html.erb
  app/views/stores/show.html.erb
  config/locales/custom.en.yml
  config/locales/custom.es.yml
Labels: 2 reviews

#57 Updated products in profile
  app/controllers/products_controller.rb
  app/models/card.rb
  app/views/cards/_card.html.erb
  app/views/cards/_edit.html.erb
  app/views/cards/_form.html.erb
  app/views/cards/_new.html.erb
  app/views/cards/destroy.js.erb
  app/views/devise/registrations/_edit.html.erb
  app/views/layouts/profile.html.erb
  app/views/products/_edit.html.erb
  app/views/products/_form.html.erb
  app/views/products/_new.html.erb
  app/views/products/_product.html.erb
  app/views/products/_product_form_content.html.erb
  app/views/products/_show.html.erb
  app/views/products/create.js.erb
  app/views/products/show.html.erb
  app/views/products/update.js.erb
  app/views/profiles/cards.html.erb
Labels: 2 reviews

#58 View abut us
  app/views/stores/index.html.erb
Labels: 2 reviews

#59 bug fix in profile form
  app/views/devise/registrations/_edit.html.erb
Labels: 2 reviews

#60 Add user.new_partner column
  app/controllers/users/registrations_controller.rb
  db/migrate/20210306041637_add_new_partner_to_users.rb
  db/schema.rb
Labels: 2 reviews

#61 Change type of column number_card to string
  db/migrate/20210306044408_change_type_number_card_to_string.rb
  db/schema.rb
Labels: 2 reviews

#64 Product delete errors
  app/controllers/products_controller.rb
  app/models/product.rb
  app/views/comments/_edit.html.erb
  app/views/comments/_form.html.erb
  app/views/products/_edit.html.erb
Labels: 2 reviews

#63 Buttom mail
  app/controllers/profiles_controller.rb
  app/views/test_emails_mailer/send_email.html.erb
Labels: 2 reviews

#42 Add skydropx
  app/models/product.rb
  config/application.rb
  lib/sky_drop_x.rb
Labels: Incomplete

#67 Add roles to the users
  app/controllers/profiles_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/user.rb
  db/migrate/20210306114224_add_role_to_users.rb
  db/schema.rb
Labels: 1 review

#68 Send order confirmation email
  app/controllers/orders_controller.rb
  app/mailers/test_emails_mailer.rb
  app/views/test_emails_mailer/order_confirmation.html.erb
Labels: 2 reviews
